name: Continuous Integration
on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
  DEPLOY_USERNAME: ${{secrets.DEPLOY_USERNAME}}
  DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
  DEPLOY_PORT: ${{secrets.DEPLOY_PORT}}
  DEPLOY_PATH: ${{secrets.DEPLOY_PATH}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Updated MLOps pipeline deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USERNAME }}
          key: ${{ env.DEPLOY_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            mkdir test
