name: Continuous Integration
on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_REPOSITORY: ${{secrets.DOCKERHUB_REPOSITORY}}
  AWS_DEFAULT_REGION: 'ap-south-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME}}
  KAGGLE_KEY: ${{ secrets.KEY}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: "app"
        run: pip install pipenv && pipenv install --dev --system --deploy

      - name: Run unit tests
        run: make unit-tests

      - name: Run quality checks
        run: make quality-checks

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Build
        run: make build

      - name: Run integration tests
        run: |
          export KAGGLE_USERNAME = ${{ env.KAGGLE_USERNAME }}
          export KAGGLE_KEY = ${{ env.KAGGLE_KEY }}
          make integration-tests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run : docker-compose push
